name: Build and Publish

on:
  push:
    tags:
      - '*'
    # branches:
    #   - master

jobs:
  # build:
  #   runs-on: ubuntu-latest

  publish:
    # needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    if: contains(github.ref, 'tags/v')
    steps:
      - uses: actions/checkout@v3

      - name: Use Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
  
      - name: Set registry url
        run: |
          pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
          pnpm config set registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Display Environment
        run: |
          echo "Current Directory: $(pwd)"
          echo "Git Head: $(git rev-parse HEAD)"
          echo "Git Branches: $(git branch -a)"
          echo "Current Registry: $(pnpm config get registry)"
      
      - name: Remove .npmrc file
        run: rm .npmrc

      - name: Publish to npm
        run: |
          pnpm run build
          pnpm publish --tag latest --access=public --no-git-checks
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
